#!/bin/bash

die () {
    echo $@
    exit 1
}

[ $# -lt 2 ] && die "usage: $(basename $0) METHOD API_URI [ -u [user:password|null|none] ] [CURL_ARGS]"

[ -n "$API_BASE" ] || die "export API_BASE=http://localhost:9000"
[ -n "$API_CRED" ] || die "export API_CRED=user:password"

M=$1; shift
P="$1"; shift

if [ "$1" = "-u" ]; then
    case "$2" in
        null|NULL|none|NONE)    U="";;
        *)                      U="-u $2";;
    esac
    shift; shift
else
    U="-u ${API_CRED}"
fi

_f=`mktemp`
trap "rm -rf $_f" EXIT

curl -s -i -X $M "${API_BASE}${P}" $U $@ | awk -v tfile="$_f" 'BEGIN { C=0 }
/^HTTP/ {print "Status: " $2}
/^\s$/ { C=1; next }
(C==1 && !/^\s$/) { print >> tfile }'

if [ -s "$_f" ]; then
    python -mjson.tool "$_f"
fi
